source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# standart gems
gem 'rails', '~> 5.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
# gem 'uglifier'
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'

# my gems
gem "haml-rails"
gem 'rails-i18n'
gem 'figaro'
gem 'bootstrap', '~> 4.1.3'
gem 'font-awesome-rails'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'sorcery'
gem 'gon'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  gem 'rspec-rails', '~> 3.6'
  # gem 'factory_girl_rails'
  gem 'database_cleaner'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :capistrano do
  gem 'capistrano', '3.9.0'
  gem 'capistrano-rvm'
  gem 'capistrano-docker', git: 'https://github.com/netguru/capistrano-docker.git'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
