source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'turbolinks', '~> 5'
gem 'sidekiq'
gem "sidekiq-cron", "~> 0.6.3"
gem 'server_metrics'

group :development, :test do
  gem 'byebug', platform: :mri
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
